name: Publish web

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install wasm-pack
        run: cargo install --locked wasm-pack
      - name: Build web
        run: mkdir _site && cd web && wasm-pack build --out-name web --out-dir ./static --target web --release && cp -r ./static/* ../_site/
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Github pages deploy
        id: deployment
        uses: actions/deploy-pages@v5