name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - fuzz_amf0_body
          - fuzz_amf3_body
    steps:
    - uses: actions/checkout@v7
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    - name: Fuzz Fuzzer
      run: cargo +nightly fuzz run --release ${{ matrix.target }} ${{ contains(matrix.target, 'amf3') && '--features amf3' || ''}} -- -max_total_time=30s

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ matrix.target }}
        path: fuzz/artifacts/
